name: Pull Request

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check for Lint
        uses: chartboost/ruff-action@v1

      - name: Check Formatting
        uses: chartboost/ruff-action@v1
        with:
          args: format --check

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - id: install-dynamodb
        name: Install DynamoDB
        uses: ./.github/actions/install-dynamodb

      - name: Install Poetry
        run: pipx install poetry

      - name: Install Dependencies
        run: poetry install --all-extras

      - name: Pytest
        run: poetry run pytest --dynamodb-dir=${{ steps.install-dynamodb.outputs.dynamodb-dir }} --cov --cov-report=xml

      - name: MyPy
        run: poetry run mypy .

      - name: Upload to Codecov.io
        uses: codecov/codecov-action@v3
